### ISSUE TITLE
Package is missing, but error message says 'No connection'

### ISSUE THREAD

**Issue by simgislab** [nextgis/metro4all-android#3]
_From @simgislab on February 21, 2015 9:0_

I forgot to put city package in place and tried to add it ... and subj.

_Copied from original issue: nextgis/metro4all#215_

**Comment by 4eRTuk** [comment]
Now shows "Getting data failed. Pleasy try reload later."

**Comment by simgislab** [comment]
correction: 'try reloading later'

**Comment by simgislab** [comment]
Или лучше "try downloading it again later"
